config/routes.rb
Rails.application.routes.draw do
  get 'friendships/create'
  get 'friendships/destroy'
  resources :user_stocks, only: [:create, :destroy]
  get 'users/my_portfolio'
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)

    client = IEX::Api::Client.new(
          publishable_token: Rails.application.credentials.iex[:ptoken] , 
            secret_token: Rails.application.credentials.iex[:stoken] ,
            endpoint: 'https://sandbox.iexapis.com/v1'
          )
      
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
      rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?    
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
    
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "Following friend"
    else
      flash[:alert] = "There was something wrong with the tracking request"
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Stopped following"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

    def search
      if params[:stock].present?
        @stock = Stock.new_lookup(params[:stock])
        if @stock
          respond_to do |format|
            format.js { render partial: 'users/result' }
          end
        else
          respond_to do |format|
            flash.now[:alert] = "Please enter a valid symbol to search"
            format.js { render partial: 'users/result' }
          end
        end    
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a symbol to search"
          format.js { render partial: 'users/result' }
        end
      end
    end
  
  end 
  

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
          stock = Stock.new_lookup(params[:ticker])
          stock.save
        end  
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
        redirect_to my_portfolio_path
    end
    def destroy
      stock = Stock.find(params[:id])
      user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
      user_stock.destroy
      flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
      redirect_to my_portfolio_path
    end        
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user    
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
    
  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result' }
        end
      end    
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">  
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><%= friend.email %></td>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td><%= link_to 'View Profile', user_path(friend),
                                          class: 'btn btn-sm btn-success' %>
              <%= link_to 'Stop following', friendship_path(friend), method: :delete, data: {confirm: 'Are you sure?'},                                          
                                          class: 'btn btn-sm btn-warning' %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
        <% if current_user %> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
                        <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
                        <%= link_to 'My Friends', my_friends_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                            <%= fa_icon 'edit' %> Edit profile
                        <% end %>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                </ul>
                <ul class='navbar-nav ml-auto'>
                    <li class='nav-item user-name'>
                        <%= fa_icon 'user' %> <%= current_user.full_name %>
                    </li>
                    <li class='nav-item'>
                        <%= link_to("Logout", destroy_user_session_path,
                            class: "btn btn-danger logout-button", method: :delete)%>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">  
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td><% if current_user.can_track_stock?(stock.ticker) %>
                  <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker),
                                    class: "btn btn-xs btn-success", method: :post %>
                <% elsif current_user.id != @user.id %>
                  <span class="badge badge-secondary">
                    You are already tracking
                    <% if !current_user.under_stock_limit? %>
                      10 stocks
                    <% end %>
                    <% if current_user.stock_already_tracked?(stock.ticker) %>
                      this stock
                    <% end %>
                  </span>
                <% end %>
              <% if current_user.id == @user.id %>
                <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'},
                                          class: 'btn btn-sm btn-warning' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Name: </strong> <%= friend.full_name %></td>
            <td><strong>Email: </strong> <%= friend.email %></td>
            <td><strong>Actions: </strong> <%= link_to "View Profile", user_path(friend),
                              class: "btn btn-sm btn-success" %>
              <% if current_user.not_friends_with?(friend.id) %>
                <%= link_to 'Follow friend?', friendships_path(friend: friend),
                              class: "btn btn-sm btn-success", method: :post %>
              <% else %>
                <span class="badge badge-secondar">
                  You are friends
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>' 

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                    class: "btn btn-xs btn-success", method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>' 

app/views/users/my_friends.html.erb
<h1>Friends</h1>
<div class='search-area'>
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="friend-results">

</div>

<% if !@friends.empty? %>
  <%= render 'friends/list' %>
<% end %> 

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class='search-area'>
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">

</div>
<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list'%>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>


<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.full_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td>
          <% if current_user.not_friends_with?(@user.id) %>
            <%= link_to 'Follow friend?', friendships_path(friend: @user),
                          class: "btn btn-sm btn-success", method: :post %>
          <% else %>
            <span class="badge badge-secondary">
              You are friends
            </span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list'%>
<% else %>
  <p class='lead'>This user is not tracking any stocks</p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'Sign out', destroy_user_session_path, method: :delete %> 